2022-04-25 00:13:22,661 INFO    MainThread:5382 [wandb_setup.py:_flush():75] Loading settings from /home/cehao/.config/wandb/settings
2022-04-25 00:13:22,661 INFO    MainThread:5382 [wandb_setup.py:_flush():75] Loading settings from /home/cehao/work/spirl/wandb/settings
2022-04-25 00:13:22,662 INFO    MainThread:5382 [wandb_setup.py:_flush():75] Loading settings from environment variables: {}
2022-04-25 00:13:22,662 INFO    MainThread:5382 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program_relpath': 'spirl/train.py', 'program': 'spirl/train.py'}
2022-04-25 00:13:22,662 INFO    MainThread:5382 [wandb_init.py:_log_setup():438] Logging user logs to ./experiments/skill_prior_learning/maze/flat/wandb/run-20220425_001322-flat/logs/debug.log
2022-04-25 00:13:22,662 INFO    MainThread:5382 [wandb_init.py:_log_setup():439] Logging internal logs to ./experiments/skill_prior_learning/maze/flat/wandb/run-20220425_001322-flat/logs/debug-internal.log
2022-04-25 00:13:22,663 INFO    MainThread:5382 [wandb_init.py:init():472] calling init triggers
2022-04-25 00:13:22,663 INFO    MainThread:5382 [wandb_init.py:init():475] wandb.init called with sweep_config: {}
config: {'exp_dir': './experiments', 'conf_path': 'spirl/configs/skill_prior_learning/maze/flat/conf.py', 'general_data_dir': './data/maze', 'general_epoch_cycles_train': 4, 'model_state_dim': 4, 'model_action_dim': 2, 'model_input_res': 32, 'model_n_input_frames': 2, 'model_batch_size': 128, 'model_n_actions': 2, 'model_split_train': 0.9, 'model_split_val': 0.1, 'model_split_test': 0.0, 'model_res': 32, 'model_crop_rand_subseq': True, 'model_max_seq_len': 300, 'model_subseq_len': 3, 'model_device': 'cuda', 'data_dataset_spec_n_actions': 2, 'data_dataset_spec_state_dim': 4, 'data_dataset_spec_split_train': 0.9, 'data_dataset_spec_split_val': 0.1, 'data_dataset_spec_split_test': 0.0, 'data_dataset_spec_res': 32, 'data_dataset_spec_crop_rand_subseq': True, 'data_dataset_spec_max_seq_len': 300, 'data_dataset_spec_subseq_len': 3, 'data_device': 'cuda', 'ckpt_path': None}
2022-04-25 00:13:22,664 INFO    MainThread:5382 [wandb_init.py:init():525] starting backend
2022-04-25 00:13:22,664 INFO    MainThread:5382 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-04-25 00:13:22,693 INFO    MainThread:5382 [backend.py:ensure_launched():219] starting backend process...
2022-04-25 00:13:22,702 INFO    MainThread:5382 [backend.py:ensure_launched():224] started backend process with pid: 5427
2022-04-25 00:13:22,703 INFO    MainThread:5382 [wandb_init.py:init():534] backend started and connected
2022-04-25 00:13:22,715 INFO    MainThread:5382 [wandb_init.py:init():598] updated telemetry
2022-04-25 00:13:22,725 INFO    MainThread:5382 [wandb_init.py:init():629] communicating run to backend with 30 second timeout
2022-04-25 00:13:23,986 INFO    MainThread:5382 [wandb_init.py:init():654] run resumed
2022-04-25 00:13:24,004 INFO    MainThread:5382 [wandb_run.py:_on_init():1922] communicating current version
2022-04-25 00:13:24,269 INFO    MainThread:5382 [wandb_run.py:_on_init():1926] got version response upgrade_message: "wandb version 0.12.15 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-04-25 00:13:24,269 INFO    MainThread:5382 [wandb_init.py:init():660] starting run threads in backend
2022-04-25 00:13:24,351 INFO    MainThread:5382 [wandb_run.py:_console_start():1896] atexit reg
2022-04-25 00:13:24,351 INFO    MainThread:5382 [wandb_run.py:_redirect():1769] redirect: SettingsConsole.REDIRECT
2022-04-25 00:13:24,352 INFO    MainThread:5382 [wandb_run.py:_redirect():1774] Redirecting console.
2022-04-25 00:13:24,354 INFO    MainThread:5382 [wandb_run.py:_redirect():1830] Redirects installed.
2022-04-25 00:13:24,354 INFO    MainThread:5382 [wandb_init.py:init():685] run started, returning control to user process
2022-04-25 00:13:57,943 INFO    MainThread:5382 [wandb_run.py:_atexit_cleanup():1865] got exitcode: 255
2022-04-25 00:13:57,953 INFO    MainThread:5382 [wandb_run.py:_restore():1837] restore
